<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticIniteb1ebc88099743d3bc8b516497f4ca56
{
    public static $prefixLengthsPsr4 = array (
        'Z' => 
        array (
            'Zend\\Stdlib\\' => 12,
            'Zend\\ServiceManager\\' => 20,
            'Zend\\Serializer\\' => 16,
            'Zend\\Math\\' => 10,
            'Zend\\Json\\' => 10,
            'Zend\\EventManager\\' => 18,
            'Zend\\Db\\' => 8,
            'Zend\\Cache\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Zend\\Stdlib\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-stdlib/src',
        ),
        'Zend\\ServiceManager\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-servicemanager/src',
        ),
        'Zend\\Serializer\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-serializer/src',
        ),
        'Zend\\Math\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-math/src',
        ),
        'Zend\\Json\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-json/src',
        ),
        'Zend\\EventManager\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-eventmanager/src',
        ),
        'Zend\\Db\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-db/src',
        ),
        'Zend\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-cache/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'V' => 
        array (
            'Valitron' => 
            array (
                0 => __DIR__ . '/..' . '/vlucas/valitron/src',
            ),
        ),
        'U' => 
        array (
            'Upload' => 
            array (
                0 => __DIR__ . '/..' . '/codeguy/upload/src',
            ),
        ),
        'P' => 
        array (
            'PHPExcel' => 
            array (
                0 => __DIR__ . '/..' . '/phpoffice/phpexcel/Classes',
            ),
        ),
        'G' => 
        array (
            'GroceryCrud' => 
            array (
                0 => __DIR__ . '/..' . '/grocerycrud/enterprise/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticIniteb1ebc88099743d3bc8b516497f4ca56::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticIniteb1ebc88099743d3bc8b516497f4ca56::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticIniteb1ebc88099743d3bc8b516497f4ca56::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
