<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Valitron' => array($vendorDir . '/vlucas/valitron/src'),
    'Upload' => array($vendorDir . '/codeguy/upload/src'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'GroceryCrud' => array($vendorDir . '/grocerycrud/enterprise/src'),
);
